[global]
pprof = ":6060"

# internet ip
addr = "127.0.0.1"

# data center id
dc = "dc1"

[log]
level = "info"
# level = "debug"

[etcd]
# ["ip:port", "ip:port"]
addrs = ["127.0.0.1:2389"]

[signal]
#listen ip port
host = "0.0.0.0"
port = "8443"
# cert= "configs/certs/cert.pem"
# key= "configs/certs/key.pem"
path = "/ws"
allow_disconnected = false

[signal.auth_connection]
enabled = true
key_type = "HMAC"  # this selects the Signing method https://godoc.org/github.com/dgrijalva/jwt-go#SigningMethod
key = ""


[signal.auth_room]
enabled = true
key_type = "HMAC"
key = ""

[nats]
url = "nats://127.0.0.1:4223"
